# Generated by Django 4.2.3 on 2023-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalEngMasterData',
            fields=[
                ('approvalEngUniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=255)),
                ('ApprovalReason', models.CharField(max_length=255)),
                ('RejectionReason', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Justification', models.CharField(max_length=255)),
                ('Remarks', models.CharField(max_length=255)),
                ('Comments', models.CharField(max_length=255)),
                ('LatestUpdateDate', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ApprovalEngMasterData',
            },
        ),
    ]
