# Generated by Django 4.2.3 on 2023-11-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(max_length=255)),
                ('leaveRequestId', models.CharField(max_length=255)),
                ('pendingActionFrom', models.CharField(max_length=255)),
                ('requestRaisedDatetime', models.DateTimeField(auto_now=True)),
                ('actionDatetime', models.DateTimeField(auto_now=True)),
                ('approvalEngUniqueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.approvalengmasterdata')),
            ],
            options={
                'db_table': 'EmpLeave',
            },
        ),
    ]
