# Generated by Django 4.2.3 on 2023-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_empleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='approvalEngUniqueID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
