# Generated by Django 4.2.3 on 2023-11-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_approvalengmasterdata_approvalenguniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalengmasterdata',
            old_name='ApprovalReason',
            new_name='approvalReason',
        ),
        migrations.RenameField(
            model_name='approvalengmasterdata',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='approvalengmasterdata',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='approvalengmasterdata',
            old_name='Justification',
            new_name='justification',
        ),
        migrations.RenameField(
            model_name='approvalengmasterdata',
            old_name='LatestUpdateDate',
            new_name='latestUpdateDate',
        ),
        migrations.RenameField(
            model_name='approvalengmasterdata',
            old_name='RejectionReason',
            new_name='rejectionReason',
        ),
        migrations.RenameField(
            model_name='approvalengmasterdata',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='approvalengmasterdata',
            old_name='Status',
            new_name='status',
        ),
    ]
