# Generated by Django 4.2.3 on 2023-11-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_rename_approvalreason_approvalengmasterdata_approvalreason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleave',
            name='id',
        ),
        migrations.AddField(
            model_name='approvalengmasterdata',
            name='flowName',
            field=models.CharField(default='unassigned'),
        ),
        migrations.AlterField(
            model_name='empleave',
            name='leaveRequestId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
