# Generated by Django 4.2.3 on 2023-11-22 10:32

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_empleave_id_approvalengmasterdata_flowname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='approvalReason',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='rejectionReason',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='status',
            field=models.JSONField(),
        ),
        
    ]





    
