# Generated by Django 4.2.3 on 2023-11-22 14:17

from django.db import migrations,connection

class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_approvalengmasterdata_approvalreason_and_more'),
    ]

    operations = [
       
    ]