# Generated by Django 4.2.3 on 2023-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20231122_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='comments',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='justification',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='latestUpdateDate',
            field=models.DateTimeField(max_length=255),
        ),
        migrations.AlterField(
            model_name='approvalengmasterdata',
            name='remarks',
            field=models.JSONField(),
        ),
    ]
