# Generated by Django 4.2.3 on 2023-11-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_empleave_actiondatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('approvalFlowId', models.IntegerField(primary_key=True, serialize=False)),
                ('approvalFlowName', models.CharField(verbose_name=255)),
            ],
            options={
                'db_table': 'ApprovalFlow',
            },
        ),
    ]
