# Generated by Django 4.2.3 on 2023-11-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_approvalflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlowHirarchies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(max_length=255)),
                ('hirarchy', models.IntegerField()),
                ('approvalFlowId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.approvalflow')),
            ],
            options={
                'db_table': 'ApprovalFlowHirarchy',
            },
        ),
    ]
