# Generated by Django 4.2.3 on 2023-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_approvalflowhirarchies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalflowhirarchies',
            name='empId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empleave',
            name='empId',
            field=models.IntegerField(),
        ),
    ]
